#!/bin/sh

git add -A
comment=`git status|grep -e deleted: -e renamed: -e modified: -e 'new file:'|tr '\n' ','|tr -s '     '|tr -d '#'|tr '\t' ' '`

echo git commit -m "$comment comment_by_`basename $0`"
git commit -m "$comment comment_by_`basename $0`"
#git push
