#!/bin/sh 

echo original name=$1
fname=${1##*/}
fname=${fname%.*}
echo fname=$fname

if [ "$1" = "" ];then
  echo usage : ${0##*/} mapfile.zip
fi

cd ~nmrihserver
unzip $1
if [ -e ${fname}.bsp ]; then
	mv ${fname}.bsp ${fname}.nav ${fname}.nmo nmrih/maps/
else
	mv ${fname}/${fname}.bsp ${fname}/${fname}.nav ${fname}/${fname}.nmo nmrih/maps/
fi

rm $1
if [ -e ${fname} ];then
	rmdir ${fname}
fi
echo ---------------_
ls -l /home/nmrihserver/serverfiles/nmrih/maps/${fname}.*
echo ---------------_
ls -l ~nmrihserver
echo end._
